### ISSUE TITLE
Cron environment variable not having impact on logrotate

### ISSUE THREAD

**Issue by cuthbeorht** [blacklabelops/logrotate#10]
Hello,

I'm trying to use the logrotate docker image.  I am overriding the LOGROTATE_CRONSCHEDULE environment variable.  However, it is not having an impact on the logrotate command.  Can you take a look?
```
environment:
        - "LOGS_DIRECTORIES=/home/logs"
        - "LOGROTATE_CRONSCHEDULE=* * * * * *"
        - "LOGROTATE_LOGFILE=/tmp/rotate-log"
        - "LGROTATE_PARAMETERS=vf"
        - "LOGROTATE_DATEFORMAT=-%Y-%m-%d-%s"
        - "LOGROTATE_COPIES=5"
```

**Comment by blacklabelops** [comment]
I will check

**Comment by blacklabelops** [comment]
Checked and even ran it even with your envs. It executes every second and works fine.

**Comment by cuthbeorht** [comment]
Awesome! Thank you for taking the time.  Then it was probably something I did.  

I appreciate your time.
