### ISSUE TITLE
how to send a signal post/pre rotate?

### ISSUE THREAD

**Issue by oppianmatt** [blacklabelops/logrotate#14]
some apps need a signal before the close the file

how do we do that with this?

**Comment by blacklabelops** [comment]
Legit question. Logrotate has some mechanisms to include pre and post scripts.

But I never got a request to implement those or hook this up with environment variables.

**Comment by blacklabelops** [comment]
Support added, description can be found here: https://github.com/blacklabelops/logrotate#custom-skript-execution
