### ISSUE TITLE
Question: will logs keep expiring when a container dies

### ISSUE THREAD

**Issue by meggarr** [blacklabelops/logrotate#19]
Hi, one quick question, if a container dies/recreated with a new container ID, and the old one is deleted, e.g. by K8s, will the rotated logs expire after the expected date?

I guess not, since the config is updated to new containers. If this is true, is there a way to handle this?
 
Thanks!

**Comment by blacklabelops** [comment]
The container id has no effect on logrotate functionality. The logrotate configuration relies solely on environment variables. As long as each container is started with the same environment variables and working on the same volumes then logrotate will function the same.

**Comment by meggarr** [comment]
Hi, I am not talking about the logrotate's container, I am talking about those target containers' logs. E.g. container abc123 's log is rotating well, by logrotate, and is having old logs
```
abc123-json.log.1.gz
abc123-json.log.2.gz
abc123-json.log.3.gz
```
Now, container abc123 dies and is deleted, logrotate's config is updated (auto), will those logs (abc123.1.gz, abc123.2.gz, abc123.3.gz) expire after e.g. 10 days?

**Comment by blacklabelops** [comment]
Depends on your configuration. The expiration is controlled by environment variable `LOGROTATE_MAXAGE`. 

There is no dependency on the target container, logrotate operates on files on mounted volumes. As long as the volumes and files remain then logrotate will continue working.
