### ISSUE TITLE
Default logrotate_croninterval invalid

### ISSUE THREAD

**Issue by daniel5gh** [blacklabelops/logrotate#2]
The default `logrotate_croninterval="1 0 0 0 * *"` (at https://github.com/blacklabelops/logrotate/blob/fe817d461a3a2f7c26d697a7f435822e3027dd24/docker-entrypoint.sh#L245) seems to be invalid. This value is used when `LOGROTATE_CRONSCHEDULE` is not set. It results in no invocations of logrotate and the following error message:
```
2016/11/21 16:40:23 Beginning of range (0) below minimum (1): 0
```

The 4th (day of month) can not be 0, it must be in range 1-31.

I am unsure what the intended value is, but I think it must be at least hourly looking at the lowest possible logrotate interval. If this is the case a cron interval of `0 0 * * * *` would work. (every hour at 0 minutes and 0 seconds).

I am working around this by providing a valid `LOGROTATE_CRONSCHEDULE` as environment var.

**Comment by blacklabelops** [comment]
Your right, the default cron seems to be faulty. The default job schedule is `daily`, therefore I will change it to `1 0 0 * * *` (first second each day).
