### ISSUE TITLE
LOGROTATE_MAXAGE does not work

### ISSUE THREAD

**Issue by jeremyzhou** [blacklabelops/logrotate#40]
configurations as below:
- name: LOGS_DIRECTORIES
value: /var/log/cmcapi
- name: LOGROTATE_COPIES
value: "3"
- name: LOGROTATE_SIZE
value: 100M
- name: LOGROTATE_MAXAGE
value: "2"            
- name: LOGROTATE_CRONSCHEDULE
value: '0 */1 * * *'

but the LOGROTATE_MAXAGE does not work. there still are 3 days logs.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/6510252/148884539-da66ddd4-0f6f-4125-9ba0-48f0403ef17e.png)

**Comment by blacklabelops** [comment]
Please check this: https://unix.stackexchange.com/questions/261696/logrotation-rotate-and-maxage-command/261705

**Comment by blacklabelops** [comment]
No further reaction. Im closing this.
